spring.application.name=Kavit
spring.datasource.url=jdbc:mariadb://localhost:3306/timetable_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true